### ISSUE TITLE
Confusef

### ISSUE THREAD

**Issue by jbadeau** [mathpaquette/tskmgr#89]
Is this meant to be a drop in replacement for nx-cloud? If so, do u have an example project?

**Comment by mathpaquette** [comment]
hello @jbadeau indeed it is. It doesn't currently offer distributed caching but offers the distributed build capability. So instead running all build tasks on the same agent/runner, this could be distributed across multiple agents. 

Look at the client-example.ts but definitely I can work towards better documentation.

Let me know if you need more help we can get in touch.
Math

**Comment by jbadeau** [comment]
Alright,

Looks interesting. We are using
https://www.npmjs.com/package/nx-remotecache-minio for distributed caching.
We are planning to creat backstage.io plug-ins to display logs and cache
hit/miss timing. I will have a look at configuring tskmgr to generate
gitlab sub pipeline. Then can looo if it makes sense to creat a backstage
ui for task execution,

**Comment by mathpaquette** [comment]
its currently being used for one large scale repo. (250+ projects) and it works pretty good.
