### ISSUE TITLE
Add "Dependency first" task scheduler support

### ISSUE THREAD

**Issue by osmolovyk** [mathpaquette/tskmgr#94]
Add feature that give us possibility to execute dependency tasks first, and make dependent tasks wait for successful completion. In case of failure all dependent tasks should be aborted.
Example: 
Project1 depends on Project2. Project2 depends on Project3.

- Tskmgr should execute Project3's task, then after successful completion execute Project2's task and only then Project3's task.
- If Project3's task failed then Project2's and Project1's task should be aborted.

**Comment by mathpaquette** [comment]
sounds like a very interesting feature.
