### ISSUE TITLE
node-fetch does not support Node.js 20

### ISSUE THREAD

**Issue by osmolovyk** [mathpaquette/tskmgr#97]
While running tskmgr client with node I am getting ECONNREFUSED error message.
To fix an issue node-fetch should be updated to latest version.
Related topic on Stackoverflow https://stackoverflow.com/questions/72390154/econnrefused-when-making-a-request-to-localhost-using-fetch-in-node-js

**Comment by mathpaquette** [comment]
we can simply remove node-fetch, fetch is now experimental in node 20
