### ISSUE TITLE
Add Kerberos authentication support

### ISSUE THREAD

**Issue by osmolovyk** [mathpaquette/tskmgr#99]
I would like to store task log files in NFS shared folder that requires Kerberos authentication. For that I need to mount this 
 folder as a volume to the API image. Mounting NFS shares with Kerberos supported by docker, but Kerberos part requires Kerberos libraries installed inside the docker image.
Task: 

- Add Kerberos libraries to API docker image.

**Comment by mathpaquette** [comment]
whats the issue. what are we trying to achieve here?
